#!/bin/sh

#DNSMASQ_DIR="/home/$USER/git/pooterbooter/dnsmasq"
DNSMASQ_DIR="/srv/dnsmasq"
DNSMASQ_CONFIG="$DNSMASQ_DIR/dnsmasq.conf"

echo "Running update and install"
sudo apt update && sudo apt install -y ufw dnsmasq nfs-kernel-server nginx ipxe pxelinux syslinux-efi php-cli php-fpm

echo "Create directories"
# Create required directories
sudo mkdir -p $DNSMASQ_DIR
sudo mkdir -p /srv/tftp/mnt/iso
sudo mkdir -p /srv/tftp/pxe/modules/bios/pxelinux.cfg # BIOS
sudo mkdir -p /srv/tftp/pxe/modules/efi32/pxelinux.cfg # EFI32
sudo mkdir -p /srv/tftp/pxe/modules/efi64/pxelinux.cfg # EFI64

# maybe later change to dnsmasq user for security
echo "Change ownership of dnsmasq & tftp"
sudo chown $USER:$USER -R /srv/$DNSMASQ_DIR
sudo chown $USER:$USER -R /srv/tftp

echo "Copy boot files"
## Copy required pxe files
cp -r /usr/lib/ipxe /srv/tftp/ipxe
cp -r /usr/lib/syslinux/* /srv/tftp/pxe
cp -r /usr/lib/PXELINUX/* /srv/tftp/pxe/modules/bios
cp -r /usr/lib/SYSLINUX.EFI/efi32/* /srv/tftp/pxe/modules/efi32
cp -r /usr/lib/SYSLINUX.EFI/efi64/* /srv/tftp/pxe/modules/efi64

### Setup dnsmasq

# Make a backup, as we are going to owerwrite it next
sudo cp -n /etc/dnsmasq.conf /etc/dnsmasq.conf.bak

# copy config from git
# TODO FIX it with config
cp -n ./dnsmasq/dnsmasq.conf /srv/dnsmasq

# if config /srv/dnsmasq/dnsmasq.conf is deleted, copy fresh
cp -n /etc/dnsmasq.conf.bak /srv/dnsmasq/dnsmasq.conf

# https://stackoverflow.com/questions/84882/sudo-echo-something-etc-privilegedfile-doesnt-work
# update main config
sudo sh -c "echo 'conf-file=$DNSMASQ_CONFIG' > /etc/dnsmasq.conf"
#(APPEND)echo "conf-file=$DNSMASQ_CONFIG" | sudo tee -a /etc/dnsmasq.conf


### Setup NFS #? nohide,crossmnt
sudo cp -n /etc/exports /etc/exports.bak # make backup

# Update main config
sudo sh -c "echo '/srv/tftp/mnt *(ro,async,no_subtree_check,no_root_squash)' > /etc/exports"
#(APPEND)echo "/srv/tftp/mnt *(ro,async,no_subtree_check,no_root_squash)" | sudo tee -a /etc/exports

# en & start svc
sudo exportfs -r

### Setup nginx
sudo cp -n /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak # make backup
# TODO FIX chown to user, copy, chown back ;(
sudo chown $USER:$USER /etc/nginx/sites-available/default
cat ./nginx/default > /etc/nginx/sites-available/default
# Fix permissions
sudo chown root:root /etc/nginx/sites-available/default
# Fix everything

#old
#sudo cp ./nginx/default /etc/nginx/sites-available/default
# #change in: /etc/nginx/sites-available/default
#
#       root /var/www/html
# to:
#       root /srv/tftp/mnt
#
# #if you want to be able to browse, add:
#
#       autoindex on;
#
# TODO nginx php

echo "Setting up firewall rules"

sudo ufw allow SSH
sudo ufw allow NFS
sudo ufw allow WWW
sudo ufw allow 67/udp # DHCP
sudo ufw allow 69/udp # TFTP
sudo ufw allow 4011/udp # PROXY
sudo ufw allow 3000/tcp # Admin

echo "Firewall:"
sudo ufw status numbered

#sudo ufw enable

echo "Setup DONE, now enable the firewall by running: sudo ufw enable"

echo "Mount disk or copy *.iso image files to /srv/tftp/mnt/iso"
